"""311 complaint-density features via spatial join (BallTree, 300 m radius).

This is the **contract-grade** implementation referenced in
``docs/interface_contracts.md``. It replaces the Phase-4 ZIP-level proxy:

  Old (ZIP-level approximation):  n_311_<type>_zip_<window>d
  New (spatial join):             n_311_<type>_300m_<window>d

Why this matters — measured on the Phase-4 features:

  The ZIP-level rodent feature had a mean of ~207 per (license, 90d). Most
  of that is noise from busy zips where the count is dominated by streets
  far from the actual restaurant. A 300-m radius gives each restaurant its
  own neighbourhood signal.

---

**Implementation**

For each sr_type we want a count for:

  1. Build a ``sklearn.neighbors.BallTree`` over the (lat, lon) of every
     event of that type, with ``metric='haversine'``.
  2. For each inspection anchor, ``tree.query_radius(point, r=300m/R_earth)``
     returns the indices of all events at coordinates within 300 m.
  3. Apply the date window: keep only events with ``created_date in
     (anchor_date - window_days, anchor_date)``. Right-exclusive of the
     anchor — see leak-guard note below.
  4. Count.

**Leak-free guard**: the date window is right-exclusive of the anchor. An
event filed ON the anchor's inspection day is excluded — that's the correct
semantics because such events are often generated BY the inspector during
the same visit.

**Cold-start / no-geo handling**: inspections with missing lat / lon get 0
for every feature. The model can learn that missing-geo means we couldn't
compute a spatial signal; it doesn't get to invent one.

**Performance**: 1.1M-row 311 file × 108k inspection anchors × 4 sr_types
runs in roughly 2-3 minutes on a laptop. The BallTree build is one-time per
sr_type; the radius queries are batched.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.neighbors import BallTree

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Earth's radius in metres. Used to convert the 300 m radius to the radian
# units that haversine BallTree expects.
EARTH_RADIUS_M: float = 6_371_000.0

# (sr_type → output_suffix → window_days). Restaurant complaints get the
# longer window because they're rarer (~22k since 2019, ~8% the volume of
# rodent / garbage). Extending here is one line.
COMPLAINT_FEATURE_SPEC: dict[str, tuple[str, int]] = {
    "Rodent Baiting/Rat Complaint": ("rodent", 90),
    "Sanitation Code Violation": ("sanitation", 90),
    "Garbage Cart Maintenance": ("garbage", 90),
    "Restaurant Complaint": ("restaurant", 180),
}

# Address-exact 311 spec (sr_type → output_suffix). Unlike the radius counts
# above, these match a complaint to the restaurant's EXACT street address —
# the open-data analog of "reviews about THIS establishment" rather than the
# surrounding block. The radius counts were flat (density confound: busy
# blocks dominate); the exact-address signal isolates the venue. One window
# (365 d) so it lines up with the prior_*_365d recency features it competes
# with. Garbage carts are excluded — they're a street-furniture issue, not a
# venue-quality signal, so a same-address match is meaningless for them.
ADDRESS_EXACT_SPEC: dict[str, str] = {
    "Restaurant Complaint": "restaurant",
    "Sanitation Code Violation": "sanitation",
    "Rodent Baiting/Rat Complaint": "rodent",
}
ADDRESS_EXACT_WINDOW_DAYS: int = 365

# Recency/trend windows for the venue's own (address-exact) 311 history. The
# "recent" window (90 d) vs the rest of the year measures acceleration — a
# *rising* spike of complaints about this venue, not a raw count. A temporal
# trend differences out any static density level, so (unlike the flat radius
# counts) it needs no neighbourhood normalisation to be meaningful.
ADDRESS_EXACT_RECENT_WINDOW_DAYS: int = 90


def add_complaint_features(
    inspections: pd.DataFrame,
    complaints: pd.DataFrame,
    *,
    radius_m: int = 300,
    inspection_date_col: str = "inspection_date",
) -> pd.DataFrame:
    """Append spatial-+-temporal 311-count features to inspections.

    Returns a new DataFrame with one ``n_311_<suffix>_<radius>m_<window>d``
    column per entry in ``COMPLAINT_FEATURE_SPEC``. Counts are ``Int32``.

    Args:
        inspections: must contain ``inspection_date`` and ``latitude``,
            ``longitude``.
        complaints: 311 dataframe; must contain ``sr_type``,
            ``created_date``, and ``latitude``, ``longitude``.
        radius_m: search radius in metres. Default 300 m matches the contract.

    Inspections with missing lat/lon get 0 for every feature (no spatial
    signal computable). The same is true for 311 rows without geo (typically
    "311 INFORMATION ONLY" entries at the city's intake address) — they are
    dropped before tree building.
    """
    out = inspections.copy()
    out[inspection_date_col] = pd.to_datetime(out[inspection_date_col])
    out["latitude"] = pd.to_numeric(out["latitude"], errors="coerce")
    out["longitude"] = pd.to_numeric(out["longitude"], errors="coerce")

    c = complaints.copy()
    c["created_date"] = pd.to_datetime(c["created_date"]).values.astype("datetime64[D]")
    c["latitude"] = pd.to_numeric(c["latitude"], errors="coerce")
    c["longitude"] = pd.to_numeric(c["longitude"], errors="coerce")
    c = c.dropna(subset=["latitude", "longitude", "created_date", "sr_type"])

    # Which inspections have computable spatial features?
    has_geo = out[["latitude", "longitude"]].notna().all(axis=1).to_numpy()
    radius_rad = radius_m / EARTH_RADIUS_M

    # Convert all anchor coordinates to radians once. We process only the
    # rows with valid geo through the BallTree; the rest will default to 0.
    if has_geo.any():
        anchor_coords_rad = np.radians(
            out.loc[has_geo, ["latitude", "longitude"]].to_numpy(dtype=np.float64)
        )
        anchor_dates = out.loc[has_geo, inspection_date_col].values.astype("datetime64[D]")
    else:
        anchor_coords_rad = np.empty((0, 2), dtype=np.float64)
        anchor_dates = np.empty(0, dtype="datetime64[D]")

    # One tree + count pass per sr_type.
    for sr_type, (suffix, window_days) in COMPLAINT_FEATURE_SPEC.items():
        col_name = f"n_311_{suffix}_{radius_m}m_{window_days}d"
        # Default for no-geo anchors is NaN — "we couldn't compute this
        # signal", not "this signal is zero". XGBoost handles NaN natively;
        # the baseline pipeline's SimpleImputer median-imputes. With-geo
        # anchors get an integer count overwritten below.
        out[col_name] = pd.array([pd.NA] * len(out), dtype="Int32")

        sub = c[c["sr_type"] == sr_type]
        if len(sub) == 0 or len(anchor_coords_rad) == 0:
            continue

        counts = _count_spatial_temporal(
            event_coords_rad=np.radians(sub[["latitude", "longitude"]].to_numpy(dtype=np.float64)),
            event_dates=sub["created_date"].to_numpy(dtype="datetime64[D]"),
            anchor_coords_rad=anchor_coords_rad,
            anchor_dates=anchor_dates,
            radius_rad=radius_rad,
            window_days=window_days,
        )

        # Map the dense counts back to the original (with-geo subset) rows.
        out.loc[has_geo, col_name] = pd.array(counts, dtype="Int32")

    return out


def add_address_exact_complaint_features(
    inspections: pd.DataFrame,
    complaints: pd.DataFrame,
    *,
    inspection_date_col: str = "inspection_date",
    window_days: int = ADDRESS_EXACT_WINDOW_DAYS,
) -> pd.DataFrame:
    """Append exact-address 311 counts to inspections.

    For each ``sr_type`` in ``ADDRESS_EXACT_SPEC`` produces one
    ``n_311_addr_<suffix>_<window>d`` column: the count of complaints of that
    type filed at the restaurant's EXACT (normalised) street address within
    the ``window_days`` before the anchor. Counts are ``Int32``.

    Unlike ``add_complaint_features`` (300 m radius, BallTree), this is a plain
    normalised-string join — exact address is a key, not a distance. It is the
    venue-level analog of consumer reviews: complaints about THIS address, not
    the surrounding block.

    Args:
        inspections: must contain ``address`` and ``inspection_date``.
        complaints: 311 dataframe; must contain ``sr_type``, ``street_address``,
            ``created_date``.

    **Leak-free guard**: the window is ``(anchor - window_days, anchor)``,
    strictly right-exclusive of the anchor date — a complaint filed ON the
    inspection day is excluded (it is often generated BY the inspector during
    the same visit, exactly as in the radius features).

    A row whose address doesn't normalise (null/blank) gets 0 for every column
    — there's no address to key on, and 0 is the honest "no matching complaint
    observed" value (addresses are present on ~100 % of inspection rows, so
    this is rare).
    """
    out = inspections.copy()
    out[inspection_date_col] = pd.to_datetime(out[inspection_date_col])
    out["_norm_addr"] = _normalize_address(out["address"])

    cols = [f"n_311_addr_{suffix}_{window_days}d" for suffix in ADDRESS_EXACT_SPEC.values()]
    for col in cols:
        out[col] = 0

    c = complaints[["sr_type", "street_address", "created_date"]].copy()
    c["created_date"] = pd.to_datetime(c["created_date"], errors="coerce")
    c["_norm_addr"] = _normalize_address(c["street_address"])
    c = c[c["sr_type"].isin(ADDRESS_EXACT_SPEC)].dropna(subset=["_norm_addr", "created_date"])

    # Stable per-row key so we can scatter per-type counts back after the join.
    out = out.reset_index(drop=True)
    out["_row"] = out.index
    anchors = out.loc[out["_norm_addr"].notna(), ["_row", "_norm_addr", inspection_date_col]]

    window_td = pd.Timedelta(days=window_days)
    for sr_type, suffix in ADDRESS_EXACT_SPEC.items():
        sub = c.loc[c["sr_type"] == sr_type, ["_norm_addr", "created_date"]]
        if sub.empty or anchors.empty:
            continue
        # Join every anchor to all same-address complaints, then keep only those
        # strictly inside the leak-free window before the anchor and count them.
        m = anchors.merge(sub, on="_norm_addr", how="inner")
        in_window = (m["created_date"] < m[inspection_date_col]) & (
            m["created_date"] > m[inspection_date_col] - window_td
        )
        counts = m.loc[in_window].groupby("_row").size()
        col = f"n_311_addr_{suffix}_{window_days}d"
        out[col] = out["_row"].map(counts).fillna(0).astype("int32")

    return out.drop(columns=["_norm_addr", "_row"])


def add_address_exact_recency_features(
    inspections: pd.DataFrame,
    complaints: pd.DataFrame,
    *,
    inspection_date_col: str = "inspection_date",
    recent_window_days: int = ADDRESS_EXACT_RECENT_WINDOW_DAYS,
    window_days: int = ADDRESS_EXACT_WINDOW_DAYS,
) -> pd.DataFrame:
    """Append recency + trend of the venue's own (address-exact) 311 history.

    Two columns, both keyed on the restaurant's EXACT normalised address (the
    same venue-level match as ``add_address_exact_complaint_features``, across
    the same ``ADDRESS_EXACT_SPEC`` complaint types):

      ``days_since_last_311_addr_complaint`` (Float64)
          Days from the most recent prior complaint at this address to the
          anchor. ``NaN`` when the venue has no prior matched complaint (the
          ~75 % of rows with no address-exact 311 history) — "never", not 0,
          so the imputer/XGBoost can tell it apart from "yesterday".

      ``trend_311_addr_complaint`` (float64)
          Acceleration: complaints in the last ``recent_window_days`` minus the
          venue's own steady-state pace over the rest of the year, i.e.
          ``n_recent - n_older * (recent_window / older_window)``. Positive =
          a rising spike about this venue; negative = cooling off; 0 = steady
          or no history. Differencing the recent window against the venue's own
          baseline cancels the static density level, so no spatial
          normalisation is needed.

    **Leak-free guard**: only complaints with ``created_date`` strictly before
    the anchor (``< as_of_date``) are used — right-exclusive of the inspection
    day, matching the count features (a same-day 311 is often filed by the
    inspector during the visit).
    """
    out = inspections.copy()
    out[inspection_date_col] = pd.to_datetime(out[inspection_date_col])
    out["_norm_addr"] = _normalize_address(out["address"])
    out = out.reset_index(drop=True)
    out["_row"] = out.index

    rec_col = "days_since_last_311_addr_complaint"
    trend_col = "trend_311_addr_complaint"
    out[rec_col] = pd.array([pd.NA] * len(out), dtype="Float64")
    out[trend_col] = 0.0

    c = complaints[["sr_type", "street_address", "created_date"]].copy()
    c["created_date"] = pd.to_datetime(c["created_date"], errors="coerce")
    c["_norm_addr"] = _normalize_address(c["street_address"])
    c = c[c["sr_type"].isin(ADDRESS_EXACT_SPEC)].dropna(subset=["_norm_addr", "created_date"])

    anchors = out.loc[out["_norm_addr"].notna(), ["_row", "_norm_addr", inspection_date_col]]
    if anchors.empty or c.empty:
        return out.drop(columns=["_norm_addr", "_row"])

    m = anchors.merge(c[["_norm_addr", "created_date"]], on="_norm_addr", how="inner")
    # Leak guard: strictly prior to the anchor. Lower-bounding at the full
    # window keeps recency/trend on the same horizon as the count features.
    age = (m[inspection_date_col] - m["created_date"]).dt.days
    m = m.assign(_age=age)
    m = m[(m["_age"] > 0) & (m["_age"] <= window_days)]
    if m.empty:
        return out.drop(columns=["_norm_addr", "_row"])

    # Recency: smallest age = most recent prior complaint.
    out[rec_col] = out["_row"].map(m.groupby("_row")["_age"].min()).astype("Float64")

    # Trend: recent count minus the venue's own steady-state expectation.
    older_window = window_days - recent_window_days
    n_recent = m[m["_age"] <= recent_window_days].groupby("_row").size()
    n_older = m[m["_age"] > recent_window_days].groupby("_row").size()
    n_recent = out["_row"].map(n_recent).fillna(0)
    n_older = out["_row"].map(n_older).fillna(0)
    out[trend_col] = (n_recent - n_older * (recent_window_days / older_window)).astype("float64")

    return out.drop(columns=["_norm_addr", "_row"])


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _normalize_address(s: pd.Series) -> pd.Series:
    """Uppercase, strip, and collapse internal whitespace for exact matching.

    Inspection addresses are uppercase with a trailing space ("608 W BARRY AVE ");
    311 addresses are mixed-case ("7517 N Western AVE"). Folding both to a single
    upper/space-collapsed form is what makes the exact join land. This is a
    deliberately simple normaliser — fuzzier matching (component parsing, typo
    repair like "BRYN WAWR"→"BRYN MAWR") is future work; the simple form already
    matches ~44 % of distinct inspection addresses.
    """
    return (
        s.astype("string")
        .str.upper()
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .replace("", pd.NA)
    )


def _count_spatial_temporal(
    event_coords_rad: np.ndarray,
    event_dates: np.ndarray,
    anchor_coords_rad: np.ndarray,
    anchor_dates: np.ndarray,
    radius_rad: float,
    window_days: int,
) -> np.ndarray:
    """Per-anchor count of events within ``radius_rad`` AND
    ``(anchor_date - window_days, anchor_date)`` (right-exclusive).

    The BallTree handles the spatial part; the date filter is a numpy mask
    applied to the per-anchor returned neighbour set. Right-exclusivity on
    the anchor date is the leak guard — same-day events are excluded.
    """
    tree = BallTree(event_coords_rad, metric="haversine")
    # Batched query — returns object array of int arrays, one per anchor.
    neighbour_indices = tree.query_radius(anchor_coords_rad, r=radius_rad)

    counts = np.zeros(len(anchor_coords_rad), dtype=np.int32)
    window_td = np.timedelta64(window_days, "D")

    # Iterate per-anchor to apply the date window. The dates inside each
    # neighbour set are typically small (tens to thousands), so this loop
    # is fast in practice.
    for i, idxs in enumerate(neighbour_indices):
        if len(idxs) == 0:
            continue
        nearby_event_dates = event_dates[idxs]
        anchor_d = anchor_dates[i]
        # Right-exclusive of anchor. Lower bound exclusive too (older events
        # don't count). Equivalently: nearby_dates in (anchor - window, anchor).
        in_window = (nearby_event_dates > (anchor_d - window_td)) & (nearby_event_dates < anchor_d)
        counts[i] = int(in_window.sum())

    return counts
