"""311 complaint-density features via spatial join (BallTree, 300 m radius).

This is the **contract-grade** implementation referenced in
``docs/interface_contracts.md``. It replaces the Phase-4 ZIP-level proxy:

  Old (ZIP-level approximation):  n_311_<type>_zip_<window>d
  New (spatial join):             n_311_<type>_300m_<window>d

Why this matters — measured on the Phase-4 features:

  The ZIP-level rodent feature had a mean of ~207 per (license, 90d). Most
  of that is noise from busy zips where the count is dominated by streets
  far from the actual restaurant. A 300-m radius gives each restaurant its
  own neighbourhood signal.

---

**Implementation**

For each sr_type we want a count for:

  1. Build a ``sklearn.neighbors.BallTree`` over the (lat, lon) of every
     event of that type, with ``metric='haversine'``.
  2. For each inspection anchor, ``tree.query_radius(point, r=300m/R_earth)``
     returns the indices of all events at coordinates within 300 m.
  3. Apply the date window: keep only events with ``created_date in
     (anchor_date - window_days, anchor_date)``. Right-exclusive of the
     anchor — see leak-guard note below.
  4. Count.

**Leak-free guard**: the date window is right-exclusive of the anchor. An
event filed ON the anchor's inspection day is excluded — that's the correct
semantics because such events are often generated BY the inspector during
the same visit.

**Cold-start / no-geo handling**: inspections with missing lat / lon get 0
for every feature. The model can learn that missing-geo means we couldn't
compute a spatial signal; it doesn't get to invent one.

**Performance**: 1.1M-row 311 file × 108k inspection anchors × 4 sr_types
runs in roughly 2-3 minutes on a laptop. The BallTree build is one-time per
sr_type; the radius queries are batched.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.neighbors import BallTree

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Earth's radius in metres. Used to convert the 300 m radius to the radian
# units that haversine BallTree expects.
EARTH_RADIUS_M: float = 6_371_000.0

# (sr_type → output_suffix → window_days). Restaurant complaints get the
# longer window because they're rarer (~22k since 2019, ~8% the volume of
# rodent / garbage). Extending here is one line.
COMPLAINT_FEATURE_SPEC: dict[str, tuple[str, int]] = {
    "Rodent Baiting/Rat Complaint": ("rodent", 90),
    "Sanitation Code Violation": ("sanitation", 90),
    "Garbage Cart Maintenance": ("garbage", 90),
    "Restaurant Complaint": ("restaurant", 180),
}


def add_complaint_features(
    inspections: pd.DataFrame,
    complaints: pd.DataFrame,
    *,
    radius_m: int = 300,
    inspection_date_col: str = "inspection_date",
) -> pd.DataFrame:
    """Append spatial-+-temporal 311-count features to inspections.

    Returns a new DataFrame with one ``n_311_<suffix>_<radius>m_<window>d``
    column per entry in ``COMPLAINT_FEATURE_SPEC``. Counts are ``Int32``.

    Args:
        inspections: must contain ``inspection_date`` and ``latitude``,
            ``longitude``.
        complaints: 311 dataframe; must contain ``sr_type``,
            ``created_date``, and ``latitude``, ``longitude``.
        radius_m: search radius in metres. Default 300 m matches the contract.

    Inspections with missing lat/lon get 0 for every feature (no spatial
    signal computable). The same is true for 311 rows without geo (typically
    "311 INFORMATION ONLY" entries at the city's intake address) — they are
    dropped before tree building.
    """
    out = inspections.copy()
    out[inspection_date_col] = pd.to_datetime(out[inspection_date_col])
    out["latitude"] = pd.to_numeric(out["latitude"], errors="coerce")
    out["longitude"] = pd.to_numeric(out["longitude"], errors="coerce")

    c = complaints.copy()
    c["created_date"] = pd.to_datetime(c["created_date"]).values.astype("datetime64[D]")
    c["latitude"] = pd.to_numeric(c["latitude"], errors="coerce")
    c["longitude"] = pd.to_numeric(c["longitude"], errors="coerce")
    c = c.dropna(subset=["latitude", "longitude", "created_date", "sr_type"])

    # Which inspections have computable spatial features?
    has_geo = out[["latitude", "longitude"]].notna().all(axis=1).to_numpy()
    radius_rad = radius_m / EARTH_RADIUS_M

    # Convert all anchor coordinates to radians once. We process only the
    # rows with valid geo through the BallTree; the rest will default to 0.
    if has_geo.any():
        anchor_coords_rad = np.radians(
            out.loc[has_geo, ["latitude", "longitude"]].to_numpy(dtype=np.float64)
        )
        anchor_dates = out.loc[has_geo, inspection_date_col].values.astype("datetime64[D]")
    else:
        anchor_coords_rad = np.empty((0, 2), dtype=np.float64)
        anchor_dates = np.empty(0, dtype="datetime64[D]")

    # One tree + count pass per sr_type.
    for sr_type, (suffix, window_days) in COMPLAINT_FEATURE_SPEC.items():
        col_name = f"n_311_{suffix}_{radius_m}m_{window_days}d"
        # Default for no-geo anchors is NaN — "we couldn't compute this
        # signal", not "this signal is zero". XGBoost handles NaN natively;
        # the baseline pipeline's SimpleImputer median-imputes. With-geo
        # anchors get an integer count overwritten below.
        out[col_name] = pd.array([pd.NA] * len(out), dtype="Int32")

        sub = c[c["sr_type"] == sr_type]
        if len(sub) == 0 or len(anchor_coords_rad) == 0:
            continue

        counts = _count_spatial_temporal(
            event_coords_rad=np.radians(sub[["latitude", "longitude"]].to_numpy(dtype=np.float64)),
            event_dates=sub["created_date"].to_numpy(dtype="datetime64[D]"),
            anchor_coords_rad=anchor_coords_rad,
            anchor_dates=anchor_dates,
            radius_rad=radius_rad,
            window_days=window_days,
        )

        # Map the dense counts back to the original (with-geo subset) rows.
        out.loc[has_geo, col_name] = pd.array(counts, dtype="Int32")

    return out


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _count_spatial_temporal(
    event_coords_rad: np.ndarray,
    event_dates: np.ndarray,
    anchor_coords_rad: np.ndarray,
    anchor_dates: np.ndarray,
    radius_rad: float,
    window_days: int,
) -> np.ndarray:
    """Per-anchor count of events within ``radius_rad`` AND
    ``(anchor_date - window_days, anchor_date)`` (right-exclusive).

    The BallTree handles the spatial part; the date filter is a numpy mask
    applied to the per-anchor returned neighbour set. Right-exclusivity on
    the anchor date is the leak guard — same-day events are excluded.
    """
    tree = BallTree(event_coords_rad, metric="haversine")
    # Batched query — returns object array of int arrays, one per anchor.
    neighbour_indices = tree.query_radius(anchor_coords_rad, r=radius_rad)

    counts = np.zeros(len(anchor_coords_rad), dtype=np.int32)
    window_td = np.timedelta64(window_days, "D")

    # Iterate per-anchor to apply the date window. The dates inside each
    # neighbour set are typically small (tens to thousands), so this loop
    # is fast in practice.
    for i, idxs in enumerate(neighbour_indices):
        if len(idxs) == 0:
            continue
        nearby_event_dates = event_dates[idxs]
        anchor_d = anchor_dates[i]
        # Right-exclusive of anchor. Lower bound exclusive too (older events
        # don't count). Equivalently: nearby_dates in (anchor - window, anchor).
        in_window = (nearby_event_dates > (anchor_d - window_td)) & (nearby_event_dates < anchor_d)
        counts[i] = int(in_window.sum())

    return counts
